# Generated by Django 2.1.4 on 2019-02-08 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [("selectielijst", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="procestype",
            name="omschrijving",
            field=models.CharField(
                help_text="Omschrijving van het procestype",
                max_length=255,
                verbose_name="procestypeomschrijving",
            ),
        )
    ]
