# Generated by Django 2.2.3 on 2020-08-07 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("selectielijst", "0009_auto_20190227_0906"),
    ]

    operations = [
        migrations.AddField(
            model_name="procestype",
            name="jaar",
            field=models.PositiveIntegerField(
                default=2017, help_text="Het jaartal waartoe dit ProcesType behoort"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="procestype",
            name="nummer",
            field=models.PositiveSmallIntegerField(
                help_text="Nummer van de selectielijstcategorie",
                verbose_name="procestypenummer",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="procestype", unique_together={("nummer", "jaar")},
        ),
    ]
