# Generated by Django 2.2.3 on 2020-08-07 14:39

import sys

from django.core.management import call_command
from django.db import migrations


def load_selectielijst_2020(apps, schema_editor):
    if sys.argv[1] != "test":
        call_command("loaddata", "src/fixtures/selectielijst_2020_fixture.json")


class Migration(migrations.Migration):

    dependencies = [
        ("selectielijst", "0010_auto_20200807_0847"),
    ]

    operations = [
        migrations.RunPython(load_selectielijst_2020, migrations.RunPython.noop)
    ]
