# Generated by Django 3.2.18 on 2023-02-15 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('selectielijst', '0012_alter_resultaat_nummer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procestype',
            name='jaar',
            field=models.IntegerField(help_text='Het jaartal waartoe dit ProcesType behoort'),
        ),
        migrations.AlterField(
            model_name='procestype',
            name='nummer',
            field=models.IntegerField(help_text='Nummer van de selectielijstcategorie', verbose_name='procestypenummer'),
        ),
    ]
