---

# Deployment

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: vrl
  namespace: gemma
  labels:
    k8s-app: vrl
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: vrl
  template:
    metadata:
      name: vrl
      labels:
        k8s-app: vrl
    spec:
      containers:
      - name: vrl
        image: vngr/vng-referentielijsten:0.1.0
        env:
          - name: DJANGO_SETTINGS_MODULE
            value: vrl.conf.docker
          - name: SUBPATH
            value: /referentielijsten
          - name: DB_HOST
            value: postgres-vrl
          - name: SECRET_KEY
            value: <REDACTED>
          - name: DB_PASSWORD
            value: <REDACTED>
          - name: SENTRY_DSN
            value: <REDACTED>

---

# Service

kind: Service
apiVersion: v1
metadata:
  name: vrl
  namespace: gemma
  labels:
    k8s-app: vrl
spec:
  selector:
    k8s-app: vrl
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
