# Generated by Django 2.1.4 on 2018-12-27 10:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CommunicatieKanaal",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "uuid",
                    models.UUIDField(
                        default=uuid.uuid4,
                        help_text="Unieke resource identifier (UUID4)",
                        unique=True,
                    ),
                ),
                (
                    "naam",
                    models.CharField(
                        help_text="De gangbare naam van het communicatiekanaal.",
                        max_length=20,
                        unique=True,
                        verbose_name="naam",
                    ),
                ),
                (
                    "omschrijving",
                    models.TextField(
                        help_text="Toelichtende beschrijving van (de naam van) het communicatiekanaal.",
                        max_length=200,
                        verbose_name="omschrijving",
                    ),
                ),
            ],
            options={
                "verbose_name": "communicatiekanaal",
                "verbose_name_plural": "communicatiekanalen",
            },
        ),
    ]
