# Generated by Django 2.1.4 on 2019-02-20 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datamodel', '0002_resultaattypeomschrijvinggeneriek'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resultaattypeomschrijvinggeneriek',
            options={'verbose_name': 'generieke resultaattypeomschrijving', 'verbose_name_plural': 'generieke resultaattypeomschrijvingen'},
        ),
    ]
